"""
Coinbase Advanced Trade Client for {strategy_name}
Generated by CBT Framework (Coinbase adapter added for this workspace)

Spot only, long only. Uses ccxt's `coinbase` exchange (Advanced Trade API).

Units (differs from the other exchange templates on purpose):
- BUY  `amount` is DOLLARS to spend (quote currency), which is what
  BaseBot._calculate_position_size() produces.
- SELL `amount` is COINS to sell (base currency).
The Kraken/Bybit/Binance templates pass the dollar size straight through as a
coin quantity, which would try to buy e.g. 100 BTC instead of $100 of BTC.

Paper mode: never sends orders and never needs API keys. It keeps a simulated
wallet (cash + coins) in logs/paper_wallet.json, fills at the live Coinbase
price plus slippage, and charges the taker fee, so paper P&L is realistic.

Live mode needs, in a git-ignored .env:
    COINBASE_API_KEY=organizations/<org_id>/apiKeys/<key_id>
    COINBASE_API_SECRET="-----BEGIN EC PRIVATE KEY-----\n...\n-----END EC PRIVATE KEY-----\n"
    COINBASE_LIVE_CONFIRM=I_ACCEPT_REAL_MONEY_RISK
Create the key at https://portal.cdp.coinbase.com with View + Trade
permissions only. Never grant Transfer, and set an IP allowlist.
"""

import json
import os
import time
import logging
from pathlib import Path

import ccxt

logger = logging.getLogger(__name__)

LIVE_CONFIRM_PHRASE = 'I_ACCEPT_REAL_MONEY_RISK'
QUOTES = ('USD', 'USDC')


class CoinbaseClient:
    """Coinbase Advanced Trade spot client with a simulated paper wallet."""

    def __init__(self, mode: str = "paper",
                 paper_starting_cash: float = 1000.0,
                 taker_fee_pct: float = 1.2,
                 slippage_pct: float = 0.05,
                 max_order_usd: float = None,
                 wallet_file: str = "logs/paper_wallet.json"):
        if mode not in ('paper', 'live'):
            raise ValueError("mode must be 'paper' or 'live'")
        self.mode = mode
        self.exchange = None
        self.taker_fee = taker_fee_pct / 100
        self.slippage = slippage_pct / 100
        self.max_order_usd = max_order_usd
        self.symbols_traded = set()

        self.wallet_file = Path(wallet_file)
        self.wallet = {'USD': paper_starting_cash}
        if mode == 'paper' and self.wallet_file.exists():
            self.wallet = json.loads(self.wallet_file.read_text())

    # ------------------------------------------------------------------ setup

    def connect(self) -> bool:
        """Connect to Coinbase. Paper mode uses public endpoints only."""
        try:
            config = {'enableRateLimit': True}

            if self.mode == 'live':
                if os.getenv('COINBASE_LIVE_CONFIRM') != LIVE_CONFIRM_PHRASE:
                    logger.error(f"Live mode refused: set COINBASE_LIVE_CONFIRM={LIVE_CONFIRM_PHRASE} in .env")
                    return False
                key = os.getenv('COINBASE_API_KEY')
                secret = (os.getenv('COINBASE_API_SECRET') or '').replace('\\n', '\n')
                if not key or not secret:
                    logger.error("Live mode needs COINBASE_API_KEY and COINBASE_API_SECRET in .env")
                    return False
                if not self.max_order_usd:
                    logger.error("Live mode needs a max order size (live.max_position_size in config.yaml)")
                    return False
                config.update({'apiKey': key, 'secret': secret})

            self.exchange = ccxt.coinbase(config)
            self.exchange.load_markets()

            if self.mode == 'live':
                self.exchange.fetch_balance()  # fail fast on bad keys

            logger.info(f"Connected to Coinbase ({self.mode})")
            return True

        except Exception as e:
            logger.error(f"Coinbase connection failed: {e}")
            return False

    # ------------------------------------------------------------------- data

    def get_latest_candles(self, symbol: str, timeframe: str, limit: int = 100) -> list:
        """Fetch OHLCV candles. Coinbase returns at most 300 per call."""
        try:
            return self.exchange.fetch_ohlcv(symbol, timeframe, limit=min(limit, 300))
        except Exception as e:
            logger.error(f"Error fetching candles: {e}")
            return []

    def _price(self, symbol: str) -> float:
        return float(self.exchange.fetch_ticker(symbol)['last'])

    def _min_cost(self, symbol: str) -> float:
        return self.exchange.market(symbol)['limits']['cost']['min'] or 1.0

    # ----------------------------------------------------------------- orders

    def place_order(self, symbol: str, side: str, amount: float,
                    order_type: str = 'market', price: float = None) -> dict:
        """
        Market orders only. BUY amount = dollars to spend; SELL amount = coins.
        Spot is long only, so a SELL with nothing held is skipped (no shorting).
        """
        if order_type != 'market':
            return {'status': 'rejected', 'reason': 'only market orders are supported'}
        try:
            self.symbols_traded.add(symbol)
            if side == 'buy':
                return self._buy(symbol, amount)
            if side == 'sell':
                held = self.get_position(symbol)['size']
                if held <= 0:
                    return {'status': 'skipped', 'reason': 'spot account cannot short'}
                return self._sell(symbol, min(amount, held))
            return {'status': 'rejected', 'reason': f'unknown side {side}'}
        except Exception as e:
            logger.error(f"Order error: {e}")
            return {'error': str(e)}

    def _buy(self, symbol: str, usd: float) -> dict:
        quote = symbol.split('/')[1]
        cash = self._free(quote)
        usd = min(usd, cash / (1 + self.taker_fee))  # leave room for the fee
        if self.max_order_usd:
            usd = min(usd, self.max_order_usd)
        usd = round(usd, 2)
        if usd < self._min_cost(symbol):
            return {'status': 'skipped', 'reason': f'order ${usd} below minimum or not enough {quote}'}

        if self.mode == 'paper':
            fill = self._price(symbol) * (1 + self.slippage)
            fee = usd * self.taker_fee
            qty = usd / fill
            base = symbol.split('/')[0]
            self.wallet[quote] = self.wallet.get(quote, 0) - usd - fee
            self.wallet[base] = self.wallet.get(base, 0) + qty
            self._save_wallet()
            return self._paper_result('buy', qty, fill, usd, fee)

        order = self.exchange.create_market_buy_order_with_cost(symbol, usd)
        return self._live_result(order['id'], symbol)

    def _sell(self, symbol: str, qty: float) -> dict:
        qty = float(self.exchange.amount_to_precision(symbol, qty))
        px = self._price(symbol)
        if qty * px < self._min_cost(symbol):
            return {'status': 'skipped', 'reason': 'position below exchange minimum (dust)'}

        if self.mode == 'paper':
            fill = px * (1 - self.slippage)
            gross = qty * fill
            fee = gross * self.taker_fee
            base, quote = symbol.split('/')
            self.wallet[base] = max(self.wallet.get(base, 0) - qty, 0.0)
            self.wallet[quote] = self.wallet.get(quote, 0) + gross - fee
            self._save_wallet()
            return self._paper_result('sell', qty, fill, gross, fee)

        order = self.exchange.create_order(symbol, 'market', 'sell', qty)
        return self._live_result(order['id'], symbol)

    def _paper_result(self, side, qty, fill, notional, fee) -> dict:
        return {
            'id': f'paper_{int(time.time() * 1000)}',
            'side': side,
            'amount': qty,
            'price': fill,
            'cost': notional,
            'fee': fee,
            'status': 'filled',
            'mode': 'paper',
        }

    def _live_result(self, order_id: str, symbol: str) -> dict:
        """Market orders fill almost instantly; poll briefly for the fill details."""
        order = {}
        for _ in range(5):
            order = self.exchange.fetch_order(order_id, symbol)
            if order.get('status') in ('closed', 'canceled', 'rejected'):
                break
            time.sleep(1)
        return {
            'id': order_id,
            'side': order.get('side'),
            'amount': order.get('filled'),
            'price': order.get('average'),
            'cost': order.get('cost'),
            'fee': (order.get('fee') or {}).get('cost', 0),
            'status': order.get('status'),
            'mode': 'live',
        }

    # -------------------------------------------------------------- positions

    def get_position(self, symbol: str) -> dict:
        """Spot position = coins held. Amounts worth less than the exchange minimum count as flat."""
        try:
            self.symbols_traded.add(symbol)
            base = symbol.split('/')[0]
            qty = self._free(base)
            if qty > 0 and qty * self._price(symbol) >= self._min_cost(symbol):
                return {'symbol': symbol, 'side': 'long', 'size': qty,
                        'entry_price': None, 'unrealized_pnl': None}
            return {'symbol': symbol, 'side': None, 'size': 0}
        except Exception as e:
            logger.error(f"Position error: {e}")
            return {'symbol': symbol, 'side': None, 'size': 0}

    def close_position(self, symbol: str) -> dict:
        """Sell everything held in symbol, or in every symbol traded this session if symbol == 'all'."""
        symbols = sorted(self.symbols_traded) if symbol == 'all' else [symbol]
        results = {}
        for s in symbols:
            pos = self.get_position(s)
            results[s] = self._sell(s, pos['size']) if pos['size'] > 0 else {'status': 'no_position'}
        return results if symbol == 'all' else results[symbol]

    # ---------------------------------------------------------------- balance

    def _free(self, currency: str) -> float:
        if self.mode == 'paper':
            return float(self.wallet.get(currency, 0.0))
        bal = self.exchange.fetch_balance()
        return float((bal.get(currency) or {}).get('free') or 0.0)

    def get_balance(self) -> float:
        """
        Total account value in USD: cash plus coins held in traded symbols,
        marked at the current price. The kill switch uses this, so a drop in
        coin value counts toward drawdown.
        """
        try:
            total = sum(self._free(q) for q in QUOTES)
            for s in self.symbols_traded:
                qty = self._free(s.split('/')[0])
                if qty > 0:
                    total += qty * self._price(s)
            return total
        except Exception as e:
            logger.error(f"Balance error: {e}")
            return 0.0

    def _save_wallet(self):
        self.wallet_file.parent.mkdir(parents=True, exist_ok=True)
        self.wallet_file.write_text(json.dumps(self.wallet, indent=2))
